### ISSUE TITLE
Entity Information Boxes

### ISSUE THREAD

**Issue by Thaerious** [Thaerious/NERVE#10]
Previously developed, currently disabled.

**Comment by Thaerious** [comment]
And will remain so.

**Comment by SusanBrown** [comment]
Can you elaborate on "And will remain so", Ed? It's essential to see more than just the label of the entity that one will be linking to. This issue may be complicated enough that it needs to wait, but I don't think it should be closed. In the interim the URL from the link address can be copied and pasted into a browser box (please ensure that this is documented, @cutic) but this is inconvenient.

**Comment by Thaerious** [comment]
The code that was disabled was deleted, having the entity show information on mouseover was too ambitious with all the other problems.  It will have to be added from scratch.  This is why the ticket was closed.
