### ISSUE TITLE
Crooked Ribs has a different format.

### ISSUE THREAD

**Issue by Thaerious** [Thaerious/NERVE#12]
The format of the Crooked Ribs file is not the same as other Orlando files.  This will result in some of the tags becoming upper case.  The cure to this is a different context, but I haven't put the context loader in yet  (a context being the file that tells the app how to behave).  Also note that the "title" tag plays two different roles, both the document title and a biblio title, where the biblio title is a taggable entity.

**Comment by ilovan** [comment]
Hi Ed, 

I might be of some help with "The format of the Crooked Ribs file is not the same as other Orlando files."
It's because the two documents reference two different schemas: the Orlando schema (the Orlando files) and the CWRC version of TEI (the Crooked Ribs and all the other Regenerations or Cultural Mapping files)

**Comment by SusanBrown** [comment]
Indeed, we need to support both schemas, Ed. We did talk about this at an earlier stage but I guess it slipped between the cracks in working on other things. We also talked about making the equivalent tags detectable and ideally also configurable, i.e. some projects will use NAME and others PERSNAME for the same entity type. We know that, but another schema might come along that uses NOM, and if we haven’t anticipated that then they need to be able to tell the program that the tag is the equivalent of PERSON in NERVE’s universe.

**Comment by Thaerious** [comment]
It does do this.

See original comment.
"The cure to this is a different context, but I haven't put the context loader in yet (a context being the file that tells the app how to behave)."

 I will have to set on up for this, but it's not on top of the list right now.

**Comment by SusanBrown** [comment]
If we have to choose at this point, then we need to privilege the other (TEI) schema, since the docs that we'll be testing NERVE on are TEI docs.

**Comment by SusanBrown** [comment]
Has this been done/the problem resolved? If so, great! If not can we move it to a later enhancement rather than closing it?
