### ISSUE TITLE
odd result when uploading a doc

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#17]
When I uploaded a document the waiting swirl appeared, but then the doc name appeared in a white box that ran along the whole space below the space where the half-width boxes of successfully uploaded docs appear. I clicked on upload again and got the same sequence: dialog from my desktip Finder, clicked on file name, then the same results.
Hopefully this screenshot will paste in.
![screenshot 2016-01-12 12 34 05](https://cloud.githubusercontent.com/assets/545952/12271493/647d336c-b929-11e5-9d05-23fc704c0be0.png)

https://www.dropbox.com/s/cueqoyqbv1nzbsd/Screenshot%202016-01-12%2012.34.05.png?dl=0

**Comment by Thaerious** [comment]
I think what happened is the conversion failed and the problem wasn't reported.  I think this is fixed now and if a conversion fails it should let you know.  Let me know if/when this occurs again.
