### ISSUE TITLE
Rename app in browser

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#25]
In browser tabs the app appears as "Web Application Starter Project"

It would be nice if it were labelled NERVE and used the CWRC logo. The new CWRC logos can be found at the links below here: we could drop the writing underneath.

https://drive.google.com/open?id=0B4CtWuyM04e4UlhKaGw5U3hIbUU
https://drive.google.com/open?id=0B4CtWuyM04e4a0dOTnhjN1BGcTQ

**Comment by Thaerious** [comment]
The name has been changed, I'm not sure why it's not showing up on your browser.  Try closing the browser down and re-opening it.  I will look into why the logo doesn't refresh, but this is not high on the list right now.

**Comment by Thaerious** [comment]
If we want to change http://beta.cwrc.ca/autoTagger/ to http://beta.cwrc.ca/nerve/ the reverse proxy has to change.

**Comment by Thaerious** [comment]
I assigned this ticket to Jeff so that he notices the last comment.

**Comment by jefferya** [comment]
Two questions:

(1) Should the autoTagger proxy be retained?

(2) Should the proxy point to "http://dh.sharcnet.ca/nerve/" or "
http://dh.sharcnet.ca/autoTagger/"

**Comment by Thaerious** [comment]
I see no reason to keep 'http://beta.cwrc.ca/autoTagger/'
it can still point to 'http://dh.sharcnet.ca/autoTagger/'  all my deploy scripts are set up to point there.

**Comment by jefferya** [comment]
I think "http://beta.cwrc.ca/nerve/" is setup. When you have a moment, can
you give it a try to verify?

**Comment by Thaerious** [comment]
beta.cwrc.ca/nerve points to the website
beta.cwrc.ca/autoTagger points to the app
This is up to Susan if it's what she wants.
In both cases I get NERVE as the tab header, it's still not updating the logo.

**Comment by SusanBrown** [comment]
beta.cwrc.ca/nerve points to the website—in both Firefox and Explorer I get a file not found message. I have to use http://beta.cwrc.ca/nerve/ <http://beta.cwrc.ca/nerve/>

beta.cwrc.ca/autoTagger points to the app—ditto above with that url. I have to put in the additional slash, i.e. http://beta.cwrc.ca/autoTagger/

This is up to Susan if it's what she wants.  — this is fine for now

In both cases I get NERVE as the tab header, it's still not updating the logo.  —same here

**Comment by Thaerious** [comment]
App is renamed, I've been having issues with the icon.  This is getting moved to beta milestone.

**Comment by SusanBrown** [comment]
Can you put in the full acronym and name, please?
NERVE: Named Entity Recognition Vetting Environment
And also a link to the Sharcnet page with the info about the project so there is somewhere to find out about it?

**Comment by Thaerious** [comment]
Where do you want the link to the SHARCNET page?

**Comment by SusanBrown** [comment]
I’d prefer if possible to put the ACRONYM with the name in small type underneath,
and the link on the top left where the folder icon is now, and to move the folder icon to the right, at the left of the box where the file name is occurring.

e.g. something like this:
<NERVE> [in bigger font, with link to Sharcnet attached to the acronym]
Named Entity Recognition Vetting Environment

**Comment by Thaerious** [comment]
I'm not entirely certain you can put two lines in a browser tab.

**Comment by SusanBrown** [comment]
Oh I wasn’t thinking in the tab—but on the top left of the page.
