### ISSUE TITLE
Dowload produces Failed-no file

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#29]

**Comment by cutic** [comment]
Tested 29 Feb 2016:

- on both PC and Mac: Failed - No file (we both worked in Chrome)

**Comment by cutic** [comment]
Download still doesn't work on either PC or Mac. 

Firefox on PC and Mac - nothing happens when you click on Download. 

Chrome on PC and Mac - Clicking on Download works, you can download a document however it still says Failed - No File. 

Documents used to test: Cultural Mapping - Mapping tags and Tagging maps and Where are you from.

I tried downloading debugCase1 document, I managed to download it but then couldn't open it in Oxygen because it couldn't be parsed.

**Comment by SusanBrown** [comment]
I tried to download quite a few files. All produced the "Failed - No file" message in the Chrome download box at the bottom of the browser window.

**Comment by abramoffcwrc** [comment]
I had no issues with downloading files (PC, Firefox and Chrome).

**Comment by SusanBrown** [comment]
@abramoffcwrc @cutic 

Can you try again and see if it still works? 

And give me step by step instructions for how to download, in case I'm missing anything?

Here's what I did: uploaded file; opened file; did some linking; clicked save; clicked download; got the dialog and entered a file name in it; got the next dialog (from my Mac) asking me to put in a file name and choose a directory, with the .txt extension already in place; changed it to xml and got a warning that the usual extension was .txt; downloaded it; it is a file containing a single world "undefined"

Any suggestions re: what I might be doing wrong?

thanks!

**Comment by abramoffcwrc** [comment]
I'm not able to download either. I simply chose a file and clicked download on both Firefox and Chrome (on PC). This is the error I got. It's a long error and I couldn't screenshot the whole thing:
![image](https://cloud.githubusercontent.com/assets/17013275/15440284/ae41ec70-1ea2-11e6-9973-46ecd6df8d31.png)

**Comment by cutic** [comment]
I get the same thing as Kristi. Doesn't even say Failed - No File, it
redirects you to this error (?).

**Comment by cutic** [comment]
Or this:

ca.sharcnet.nerve.fileservices.decode.DecoderExceptionThe entity "nbsp" was
referenced, but not declared.cause: org.xml.sax.SAXParseExceptioncause: The
entity "nbsp" was referenced, but not declared.

**Comment by Thaerious** [comment]
I will look into it.   I am not near a computer right now.   Is it doing this repeatedly? 


Sent from my Samsung device

-------- Original message --------

**Comment by cutic** [comment]
Yes. I tried several different documents. This is a screenshot of the other error it redirects me to. 
![download error](https://cloud.githubusercontent.com/assets/17013268/15440598/82a42b46-1e93-11e6-9d04-ad293097ce73.jpg)

**Comment by cutic** [comment]
It redirects me to one of these even after clearing cache.

**Comment by cutic** [comment]
Tested it again: I was able to download 1. Cultural Mapping - Foreword (twice).

Still have problems with other documents (download redirects to one of the above mentioned errors), tried several.

**Comment by SusanBrown** [comment]
Yes I tried it on a number of files, and Anita has tried also and confirmed there is a problem.

**Comment by cutic** [comment]
Managed to download 10. Salomania as well.

**Comment by SusanBrown** [comment]
I’ve downloaded several files successful. Not clear what was going on, but woohoo! It seems to be working now. Thanks for the testing, everyone! I’ll be testing more over the weekend but the files are looking good in Oxygen.

**Comment by cutic** [comment]
I can test again tomorrow too.

**Comment by cutic** [comment]
I have tried downloading a few different files (on my PC), got this:

![crop](https://cloud.githubusercontent.com/assets/17013268/15449772/a021c0be-1f44-11e6-982c-7dd8f376be2e.png)
