### ISSUE TITLE
Tab Naming and Icon

### ISSUE THREAD

**Issue by Thaerious** [Thaerious/NERVE#3]
In order to make it useful for testing, we need to add the title tag asap, or make it super easy to do so at startup. I did so very easily, so perhaps it's fine as is, but it would be nicer if it were already there since it will be a given in every use of this tool by Orlando or CWRC.

**Comment by Thaerious** [comment]
By tab do you mean the browser tab?

**Comment by SusanBrown** [comment]
Yes.

**Comment by Thaerious** [comment]
Fixed, and I added a different Icon, sometimes the icon doesn't refresh though.
