### ISSUE TITLE
Backspace key on mac (says delete on the keyboard) is not working to remove entities

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#30]

**Comment by Thaerious** [comment]
Backspace should now do the same thing as delete.  It will no longer go to previously browsed page.  Active with next push.

**Comment by SusanBrown** [comment]
Still same as before: next push still pending?

**Comment by Thaerious** [comment]
merged with ticket https://github.com/Thaerious/NERVE/issues/46
