### ISSUE TITLE
Make it possible to substitute a different string to search on in the lookups for links

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#37]
[apologies if this is a duplicate]

So if someone is tagging "He", they need to be able to put "Winston Churchill" into the lookups

**Comment by Thaerious** [comment]
I'm moving this to beta/enhancement.  This is actually going to be a rather involved addition.

**Comment by SusanBrown** [comment]
It seems to work. I just retested it and I think it works fine.

**Comment by SusanBrown** [comment]
Confirmed again that this works.
