### ISSUE TITLE
Exception error when adding entity from CWRC

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#39]
I'm logged into CWRC and able to look up entities but when I select one I get the following error:

Exception ThrownxClose
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot set property 'c' of undefined
(TypeError) : Cannot set property 'c' of undefined
- Exceptions.java:36
- TaggedEntityCollection.java:60
- CWRCLinkForm.java:58
- ClickEvent.java:56
- SimpleEventBus.java:194
- HandlerManager.java:127
- Widget.java:129
- DomEvent.java:125
- Widget.java:177
- Widget.java:163
- DOM.java:1480
- DOMImplStandard.java:317
- Impl.java:247
- Impl.java:299
- Impl.java:72

**Comment by Thaerious** [comment]
I have been amalgamating all the link dialogs into one.  Currently it seems to ignore the fact that I am logged into CWRC.  I hope to get this up and running tomorrow (16-02-24)... hope is a strong word.

**Comment by SusanBrown** [comment]
Good luck and thanks for the update!

**Comment by cutic** [comment]
Here is the error we get when trying to link names to CWRC: 

![cwrc_error](https://cloud.githubusercontent.com/assets/17013268/13439609/8c65a398-dfab-11e5-9aaf-04fada9fcc46.png)

**Comment by Thaerious** [comment]
I'm fairly certain this issue was resolved when I merged the lookups together.
