### ISSUE TITLE
Save button

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#41]
Tested on 29 Feb 2016:

-  save button doesn’t save changes neither on PC nor on Mac

- double clicking the title in the dialogue window saves changes on both PC and Mac (Kristi and I both feel like this should be explained better because it is not intuitive)

**Comment by Thaerious** [comment]
This does not seem right at all.

**Comment by cutic** [comment]
Seems to work now.

**Comment by Thaerious** [comment]
Hopefully this works now, leaving as high priority until confirmed.

**Comment by cutic** [comment]
Save button in the dialogue window works, it save all the work done in a document. But there is still no Save button on the main screen and we (Kristi and I) feel like this might be useful. When you want to Save your work it makes more sense to be able to do it in the same window without having to open the documents window. I don't know if that is something you want to bring back or just keep Save in the dialogue box, but having the Save button in the main window will be more user friendly.

**Comment by Thaerious** [comment]
My major concern is that it works, reorganization/interface issues are next phase.

**Comment by SusanBrown** [comment]
Agree. We want the functionality rock solid before we start to deal with such interface issues. Please tag them as interface and we will bracket them for the time being.
