### ISSUE TITLE
Tag/Untag/Customize Pop Up

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#42]
Tested on 29 Feb 2016:

- On **Mac computer** when you right click on a tagged term in the text area no pop up box appears (Tag / Untag / Customize) but it does on PC and it works on PC 

- on Mac if you want to tag/untag/customize a term in the text area you highlight a term and then press ctrl-e which then opens the Customize entity window and that works (it works on PC too)

- right clicking on lemmas in the left hand side panel opens a pop up Tag / Untag / Customize on both Mac and PC

**Comment by Thaerious** [comment]
Odd, I must be handling the events differently.  I'll look into it.

**Comment by Thaerious** [comment]
Disabled the clear on mouse press for right button presses.  Seems to work, will be updated on next push.
