### ISSUE TITLE
Highlighting text 

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#43]
Tested on 29 Feb 2016:

- when you are trying to highlight a larger portion of text quotation marks and tagged terms are not highlighted 

![highlighting](https://cloud.githubusercontent.com/assets/17013268/13440398/138fc710-dfaf-11e5-85e5-24a25b3178df.png)

- if you press **ctrl-a** it highlights everything except for quotation marks 

![highlighting_ctrl-a](https://cloud.githubusercontent.com/assets/17013268/13440443/4838bbe8-dfaf-11e5-8e49-8712666a3cf3.png)

**Comment by Thaerious** [comment]
Ctrl-A should be disabled altogether.  What system/browser are you using?

**Comment by Thaerious** [comment]
Let me correct myself, ctrl-a selects all matching tags.  I disabled the default behavior because it can wreck havoc on the gui.

**Comment by Thaerious** [comment]
I have disabled quote replacement (and apostrophe) ampersand replacement still exists.

**Comment by cutic** [comment]
I was working on Mac, in Chrome

**Comment by Thaerious** [comment]
cmd-a still activates select all.  The problem is detecting mac command key presses is a bit more of a convoluted system then detecting control key presses.  While I will fix this, it's on the bottom of the pile for now.  Unless of course you actually pressed ctrl-a, in which case I can't recreate the problem.

**Comment by cutic** [comment]
You can now highlight quote marks and tagged terms in the text pane in Firefox (Mac). 

In Chrome tagged entities do not get highlighted (document tested: Cultural Mapping - Mapping tags and Tagging maps) on both PC and Mac.
