### ISSUE TITLE
Top of page cut off 

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#44]
- Top of the page seems to be cut off - Kristi and I think it happens when you're viewing it on smaller sized screens  

![top_of_page](https://cloud.githubusercontent.com/assets/17013268/13440504/9af6c56e-dfaf-11e5-8e67-310a1a48de40.png)

- the drop down boxes seem to be cut off if viewed on smaller sized screens 

![drop_down_box](https://cloud.githubusercontent.com/assets/17013268/13440934/dfcadf52-dfb1-11e5-9536-61e2fc9d43a0.png)

**Comment by Thaerious** [comment]
What file were you using when this happened?  I can't seem to recreate the issue, but I was going to move the buttons and text bar together regardless.  We'll see if that helps.

**Comment by cutic** [comment]
It was different files, but the screen size was 13 inches

**Comment by Thaerious** [comment]
I am changing all of the dimensions to be by percentage instead of absolute. This should fix most problems but i'll have to have a look at text and image sizes.

**Comment by Thaerious** [comment]
Fixed, missed a px -> pct change.. Added resized images for the buttons.
