### ISSUE TITLE
Remarks on the new version of NERVE

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#50]
-  Introductory help text provided has not been added so there is no guidance when encountering the tool.

- There is no save button on the main page and no download button on the main page which might be really helpful and they were there in the previous version. This is counter intuitive.

- The whole NERVE page is not very intuitive, it looks like it might not have loaded properly (this is what I first thought when I first opened NERVE).

**Comment by SusanBrown** [comment]
Hi Anita,

Could you please break these up into single tickets with a bit more specific suggestion--I thinks there is already one for the intro text for instance, so just flag it as high priority perhaps?--and then resolve this one? 
I agree that the first page should ideally have better styling but it's more important to get the funtionality problems sorted out so it's usable as we have projects that really need to use this (even more than the DToC one, in fact).
thanks!

**Comment by Thaerious** [comment]
This can be added, but anything that isn't core functionality will be put off for the time being. For alpha it basically boils down to (1) is there a way to accomplish it, (2) does that way work.  This ticket will be closed as most things are covered in other tickets.
