### ISSUE TITLE
Graphic Issues

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#51]
1. **Title cut off**

- document used for testing: Cultural Mapping - Mapping Tags and Tagging Maps
- problem: when the title is longer it goes in two rows, and the bottom row is then cut off, but if you enlarge your window the title does get pulled back up into one row - Chrome and Firefox on Mac; PC Firefox and Chrome - no problems

![title cut](https://cloud.githubusercontent.com/assets/17013268/14973027/5be85140-10a0-11e6-8f0f-2431d6946d04.jpg)

2. **Resizing** browser window and NERVE  

On Mac in both Chrome and Firefox, when I resize the browser window, NERVE window doesn’t resize as well, the folder image is cut off.

![folder cut](https://cloud.githubusercontent.com/assets/17013268/14973056/b390a24e-10a0-11e6-95cb-3b7243c3f81f.jpg)

3. **Random text boxes** appears on the top of the page when clicking on larger chunks of text in the left hand panel. (tested on duncsa-b-launchdoc).

![text box random](https://cloud.githubusercontent.com/assets/17013268/14973093/fb31df3c-10a0-11e6-9b81-0e3a6af141bc.jpg)

4. On smaller screens (13 inch or smaller) **drop-down menus/boxes are cut off**. 

5. **Graphics missing**

- on PC: Firefox and Chrome - no graphics at all (document tested: Mapping tags and Tagging Maps)
- on Mac: graphics (e.g. the plus sign when dragging entities from text pane to the left hand panels) show up in Chrome, not in Firefox

![graphics missing](https://cloud.githubusercontent.com/assets/17013268/14973255/bd2b5360-10a2-11e6-9625-dda6f992aca9.jpg)

6. When it comes to purple boxes indicating Place, Names, etc. on the bottom, beneath the last one there’s one purple box that’s narrower than the rest of them. Is it supposed to do something? Maybe remove it? Visually weird and might be confusing because it doesn’t really indicate anything, it is just there. (both Chrome and Firefox on Mac and PC, various documents tested)

![purple box bottom](https://cloud.githubusercontent.com/assets/17013268/14973338/a2e26d30-10a3-11e6-9612-5b6aa1d2d7a9.png)

**Comment by Thaerious** [comment]
As of the next push the maximum title size has been set to 16 characters.  This only applies to the title display, not the actual filename.  I'll close this ticket for now, feel free to reopen it if the problem persists.

**Comment by cutic** [comment]
That makes things a little complicated because now that the title has been set to 16 characters, if you have multiple documents that begin with the same words you don't know which specific document you're in, e.g. Cultural Mapping - Where are you from?, Cultural Mapping - Mapping tags and tagging maps, etc. 

Because you cannot rename the title of documents in the Load File it is a bit complicated to do it that way. 

![screen shot 2016-05-04 at 1 46 53 pm](https://cloud.githubusercontent.com/assets/17013268/15027091/1a40bb28-11ff-11e6-8132-04d2748ee73c.png)
