### ISSUE TITLE
nothing on the right click menu within the text pane is working:

### ISSUE THREAD

**Issue by Thaerious** [Thaerious/NERVE#62]
In fact, nothing on the right click menu within the text pane is working:
UnTag is still not working.

Customize Tag is throwing up an exception error:
java.util.NoSuchElementException
- Throwable.java:116
- Cast.java:321
- RuntimeException.java:25
- NoSuchElementException.java:25
- InternalPreconditions.java:59
- AbstractList.java:49
- EntityPanelPopupMenu.java:49
- PopupMenu.java:128
- ClickEvent.java:56
- SimpleEventBus.java:193
- HandlerManager.java:127
- Widget.java:129
- DomEvent.java:125
- Widget.java:177
- Widget.java:163
- DOM.java:1480
- DOMImplStandard.java:317
- Impl.java:247
- Impl.java:299
- Impl.java:72

**Comment by Thaerious** [comment]
Can not recreate.

**Comment by abramoffcwrc** [comment]
I cleared my cache and this works for me on Chrome. Only un-tagging entities works in Firefox.
