### ISSUE TITLE
Ctrl M tags entities but doesn't let you drag them into the left panel except if tagging with an existing entity

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#65]
You can drag them onto an entity name but if you drag them onto the header or the white space at the bottom of the list for the entity type then nothing happens: it stays apparently tagged but the lemma is not added to the list.

**Comment by abramoffcwrc** [comment]
I had no problem with this on PC in Firefox or Chrome (using 8. Cultural Mapping - Edmonton pipeline).

**Comment by Thaerious** [comment]
I can not recreate this issue, it may have been inadvertently fixed with the last large patch.  I'm going to close it for now but reopen if it reoccurs.
