### ISSUE TITLE
Random error messages when opening documents

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#69]
Both PC and Mac, 12. Where are you from?

This one shows up in Chrome:
![screen shot 2016-05-16 at 2 15 16 pm](https://cloud.githubusercontent.com/assets/17013268/15302626/24411480-1b71-11e6-82e6-54073eabbcf8.png)

This one shows up in Firefox:
![screen shot 2016-05-16 at 2 17 08 pm](https://cloud.githubusercontent.com/assets/17013268/15302609/0fc70aa0-1b71-11e6-903d-29a882925de0.png)

**Comment by Thaerious** [comment]
Clear your cache that's the old load file, but on a side note something is going wrong with files right now.

**Comment by Thaerious** [comment]
This is related to the html/xml difference in self terminating tags.  There is a work-around now up.
