### ISSUE TITLE
Although logged into CWRC, can't get list of CWRC entity links

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#7]
I'm having no problems with the Geonames lookup.

When trying to link to names, sometimes I get the message saying that I haven't logged into the CWRC beta site, even though I have, and sometimes I get this message:

java.lang.NullPointerException: TEC not set.
TEC not set.
- Throwable.java:116
- Exception.java:29
- RuntimeException.java:29
- NullPointerException.java:29
- GenericLinkForm.java:40
- GenericLinkForm.java:39
- PopupPanel.java:512
- DropFlowListener.java:256
- CWRCLookup.java:38
- Request.java:250
- RequestBuilder.java:412
- XMLHttpRequest.java:329
- Impl.java:247
- Impl.java:299
- Impl.java:72

**Comment by Thaerious** [comment]
I couldn't replicate this bug, reopen the ticket if it happens again.

**Comment by SusanBrown** [comment]
Alas it persists. 

Tried to link entity in file. Got error message. Clicked through to site and logged in. Got the following error:
![screenshot 2016-01-12 12 34 05](https://cloud.githubusercontent.com/assets/545952/12274933/47d5205a-b93b-11e5-9406-bdb4a1a13fd7.png)

Closed that file and opened another one. Got this error:
![screenshot 2016-01-12 12 40 22](https://cloud.githubusercontent.com/assets/545952/12274944/543f06bc-b93b-11e5-8211-e9306d8e3eb0.png)

Closed NERVE and reopened a file. Got this error:

![screenshot 2016-01-12 14 48 42](https://cloud.githubusercontent.com/assets/545952/12275002/a612a476-b93b-11e5-9441-a7f9946624d9.png)

**Comment by Thaerious** [comment]
Is this the CWRC lookup error?  It looks like the ongoing Salomania bug.

**Comment by SusanBrown** [comment]
this is not limited to Salomania. This is occurring with the Representing Canadian ... file as well. I have got the Links command to work once, by selecting an entity in the left panel and hitting the L key, but I get an exception error in the right panel all the time, and sometimes in the left. Text of one of the exception errors:

java.lang.NullPointerException: TEC not set.
TEC not set.
- Throwable.java:116
- Exception.java:29
- RuntimeException.java:29
- NullPointerException.java:29
- GenericLinkForm.java:40
- GenericLinkForm.java:39
- PopupPanel.java:512
- DropFlowListener.java:222
- CWRCLookup.java:38
- Request.java:250
- RequestBuilder.java:412
- XMLHttpRequest.java:329
- Impl.java:247
- Impl.java:299
- Impl.java:72

**Comment by Thaerious** [comment]
I can not reproduce this error, I'm going to have to see it in person.

**Comment by SusanBrown** [comment]
Haven't seen this in a while so am resolving.
