### ISSUE TITLE
Save button doesn't work

### ISSUE THREAD

**Issue by abramoffcwrc** [Thaerious/NERVE#70]
Save button doesn't work on PC or Mac, Firefox or Chrome.

**Comment by Thaerious** [comment]
Looking into it.

**Comment by Thaerious** [comment]
Also as a side note, CTRL-S seems to be disfunctional.

**Comment by Thaerious** [comment]
This has been fixed and will be updated today.

**Comment by Thaerious** [comment]
fixed.
