### ISSUE TITLE
Scrolling to the side to read documents

### ISSUE THREAD

**Issue by abramoffcwrc** [Thaerious/NERVE#74]
When reading a document I have to scroll to the side. This isn't a huge deal but on some documents you have to scroll a lot. The following example happens on PC on Firefox and Chrome, using Languages Languages.
![image](https://cloud.githubusercontent.com/assets/17013275/15411312/1886695a-1ded-11e6-92c4-8bdcfe18892b.png)

**Comment by cutic** [comment]
My screen is pretty big so this didn't happen. When I make the browser window smaller, this happens. 

Could there be an option to collapse/minimize/maximize the text pane and the left hand side pane?

**Comment by abramoffcwrc** [comment]
Closing this issue as it is the same as #96.
