### ISSUE TITLE
Right Click Has Stopped Working

### ISSUE THREAD

**Issue by Thaerious** [Thaerious/NERVE#78]

**Comment by cutic** [comment]
Yes. I'm assuming we might want to wait until you've had a chance to look at it before testing it again?

**Comment by Thaerious** [comment]
Note not a high priority bug as it doesn't break the program.  The menu options and keyboard shortcuts are still available.  I am looking into why the right click menu stopped working.

**Comment by Thaerious** [comment]
Found it and fixed it, will be in the next push.

**Comment by SusanBrown** [comment]
Hurray! Thanks for all these fixes, Ed. I’m at a conference and run off my feet but hoping, Anita and Kristi, that you can find time to test the fixes.

**Comment by cutic** [comment]
Right click is working now.
