### ISSUE TITLE
Download produces exception error

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#79]
I just did a lot of testing of NERVE and then got an exception error up on attempting to download the file. 

The file is called: Brodie, Leanna v18asdownloaded.xml

I will do some more testing now.

Exception error is this:

org.w3c.dom.DOMException

INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified.

com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.createAttribute(CoreDocumentImpl.java:568)

com.sun.org.apache.xerces.internal.dom.ElementImpl.setAttribute(ElementImpl.java:498)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.unwrap(FormatDecoder.java:130)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.process(FormatDecoder.java:109)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.process(FormatDecoder.java:111)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.process(FormatDecoder.java:111)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.process(FormatDecoder.java:111)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.decode(FormatDecoder.java:78)

ca.sharcnet.nerve.fileservices.Restore.processRequest(Restore.java:114)

ca.sharcnet.nerve.fileservices.accounts.abstractservlets.CustomServlet.doPost(CustomServlet.java:122)

javax.servlet.http.HttpServlet.service(HttpServlet.java:648)

javax.servlet.http.HttpServlet.service(HttpServlet.java:729)

org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)

org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)

org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)

org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)

org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)

org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)

org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)

org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)

org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)

org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)

org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)

org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)

org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)

java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

java.lang.Thread.run(Thread.java:745)

**Comment by Thaerious** [comment]
These should be fixed now.
