### ISSUE TITLE
orgnames seem under-represented

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#8]
NERVE seems not to find orgnames when it should, and at least sometimes to be misreading orgnames as places. 

In the Salomania file it finds no orgnames at all.
This is despite the fact that there are orgnames already tagged in the document--they aren't populating the lefthand panel at all.

In Cultural Mapping L'espace ensocele, however, it does identify several orgnames (I haven't checked but these are probably not already tagged but the result of NER

**Comment by Thaerious** [comment]
Please indicate where in the Salomaniav file orgnames is already tagged.  The file I am specifically looking at is "Cultural Mapping - Salomaniav1.xml".

**Comment by ilovan** [comment]
Places, names and organizations are not tagged at all in the Salomania file. 
It's not that uncommon to have less organizations or less places, etc.  - depending on the subject of the article.
