### ISSUE TITLE
Prevent user from navigating away from page without confirming

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#84]
Not a bug but a huge priority because very easy to do with inadvertent swipe on a Mac

**Comment by Thaerious** [comment]
Please add a description about what is going on.  I'll see if I can do something about it.  Note if you want this to actually be a high priority, other bugs will be left.  I would not call this a bug, this isn't an error in code, but an omission that needs to be added.  Bugs are unexpected behavior, this is expected but undesired.

**Comment by SusanBrown** [comment]
Yes, I know it's not technically a bug. But it will be a serious problem if not addressed. I could make a different label if you want!

The issue is that on a Mac you can easily end up swiping your trackpad by mistake and inputting the equivalent of hitting a back button. With NERVE as it is now, you lose everything since your last save.

It is a common functionality on web pages that involve filling in a form that the page will not let you navigate off of the current page without giving you a warning that you will lose your stuff.  Below is what it looks like in CWRC-Writer. I think this is what we need. It is quite dumb: it gives you the message whether you've done anything or not. In other words, it can be in place all the time; better than having people lose their work.

Alternatively, we could implement autosave but I think this would be a better way to go.

![image](https://cloud.githubusercontent.com/assets/545952/15507387/689d884c-2199-11e6-8b08-1fd2ca33a31e.png)

**Comment by Thaerious** [comment]
I've added a warning, It'll be live with the next push.   And I think we need a 'normal priority' bug.

**Comment by Thaerious** [comment]
Ok this should be good now, closing the ticket.
