### ISSUE TITLE
Preface of Cultural Mappings downloads find

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#86]
I was able to upload and download a Cultural Mappings file and downloaded it in XML successfull. It's full of validation errors and I don't know why yet: need to do more testing. But at least Iw as able to download it without the exception error. This suggests that the problems have to do with the CWRC and Orlando, as opposed to the TEI schema. Will try to investigate more this morning.

**Comment by Thaerious** [comment]
What exactly do you mean by validation errors?

**Comment by SusanBrown** [comment]
I meant that when I open it in Oxygen it's full of errors when I validate it. I don't know why--didn't have a chance to check. Am going to lay out a series of test and ask @cutic and @abramoffcwrc to work through them as soon as possible.

**Comment by cutic** [comment]
Managed to upload the 4 files Susan chose as test files, no validation errors in Oxygen and they all seemed to upload and process successfully in NERVE. Uploaded one document from Cultural Mapping as well, seemed to work well.

**Comment by cutic** [comment]
Tried to download one of the uploaded documents: Brodie, Leanna (18) VR4.xml and it redirected me to this exception (working on PC): 

org.w3c.dom.DOMException

INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified.

com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.createAttribute(CoreDocumentImpl.java:568)

com.sun.org.apache.xerces.internal.dom.ElementImpl.setAttribute(ElementImpl.java:498)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.unwrap(FormatDecoder.java:130)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.process(FormatDecoder.java:109)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.process(FormatDecoder.java:111)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.process(FormatDecoder.java:111)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.process(FormatDecoder.java:111)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.decode(FormatDecoder.java:78)

ca.sharcnet.nerve.fileservices.Restore.processRequest(Restore.java:114)

ca.sharcnet.nerve.fileservices.accounts.abstractservlets.CustomServlet.doPost(CustomServlet.java:122)

javax.servlet.http.HttpServlet.service(HttpServlet.java:648)

javax.servlet.http.HttpServlet.service(HttpServlet.java:729)

org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)

org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)

org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)

org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)

org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)

org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)

org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)

org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)

org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)

org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)

org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)

org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)

org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)

java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

java.lang.Thread.run(Thread.java:745)

**Comment by cutic** [comment]
Same with the other three test documents: Cooper, Beverley (02) VR7.xml, Williams, Deborah (14) VR3.xml.

I was able to download 3. Cultural Mapping - Tagging maps and mapping tags. Opened it in Oxygen, no validation errors.

**Comment by cutic** [comment]
I cleared cache before every download.

**Comment by SusanBrown** [comment]
Good idea. Please add to the test protocol as a reminder, if you would.
thanks!

**Comment by abramoffcwrc** [comment]
I haven't had problems uploading to NERVE, but when downloading I get that error too. I'm working on PC and it happens in both Chrome and Firefox.

**Comment by Thaerious** [comment]
The next push fixes a number of downloading errors.  To test it reupload the file and then try downloading again.

**Comment by cutic** [comment]
I uploaded Cooper, Beverly (02) VR7.xml, downloaded it without changing anything in it in NERVE, got a bunch of validation errors when I opened it in Oxygen (prior to uploading, it had only one validation error). Same with Brodie, Leanna (18) VR4.xml. (no validation errors before uploading it to nerve).

**Comment by cutic** [comment]
That being said, download seems to be working now.

**Comment by Thaerious** [comment]
I will need to know what the actual error is.  I don't know what "oxygen" is.  If it's just telling you what is invalid with the xml, pass on the results and I might be able to do something with those.

**Comment by Thaerious** [comment]
Moving to ticket https://github.com/Thaerious/NERVE/issues/92
