### ISSUE TITLE
Error when trying to download 3. Cultural Mapping.

### ISSUE THREAD

**Issue by abramoffcwrc** [Thaerious/NERVE#87]
I got this error, which is different than other errors I've gotten when downloading.

ca.sharcnet.nerve.fileservices.decode.DecoderException

XML document structures must start and end within the same entity.

cause: org.xml.sax.SAXParseException

cause: XML document structures must start and end within the same entity.

com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)

com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)

javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.decode(FormatDecoder.java:60)

ca.sharcnet.nerve.fileservices.Restore.processRequest(Restore.java:114)

ca.sharcnet.nerve.fileservices.accounts.abstractservlets.CustomServlet.doPost(CustomServlet.java:122)

javax.servlet.http.HttpServlet.service(HttpServlet.java:648)

javax.servlet.http.HttpServlet.service(HttpServlet.java:729)

org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)

org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)

org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)

org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)

org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)

org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)

org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)

org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)

org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)

org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)

org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)

org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)

org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)

java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

java.lang.Thread.run(Thread.java:745)

**Comment by cutic** [comment]
I get the same error.

**Comment by Thaerious** [comment]
The next push fixes a number of downloading errors.  To test it reupload the file and then try downloading again.

**Comment by abramoffcwrc** [comment]
I can now download on PC on Firefox and Chrome, but get this error when I open the document in Author mode in Oxygen.

![image](https://cloud.githubusercontent.com/assets/17013275/15695116/df285a54-2771-11e6-81a5-59bcda56a7f6.png)

**Comment by Thaerious** [comment]
I don't know what Oxygen is and I can't really fix anything to do with it until I do.  The only link I have have found is for a proprietary software package.

**Comment by Thaerious** [comment]
Move to ticket https://github.com/Thaerious/NERVE/issues/92
