### ISSUE TITLE
Lemma bars randomly have \n in them. 

### ISSUE THREAD

**Issue by abramoffcwrc** [Thaerious/NERVE#88]
This happened on PC in Firefox and Chrome.

![image](https://cloud.githubusercontent.com/assets/17013275/15630734/4976abfe-2515-11e6-9941-82598bd0b936.png)

**Comment by cutic** [comment]
Yes, noticed this too in some documents, e.g. Whitehorn, Chloe (15) VRK.xml in Orgnames, Date, Place, Name and Title.

**Comment by Thaerious** [comment]
That's probably a debugging method that didn't get removed.  I'll hunt it down.

**Comment by Thaerious** [comment]
This may have self-corrected with the last push.  Closing ticket until it reoccurs.
